[package]
name = "router"
version = "0.1.0"
edition = "2021"

[dependencies]
core = { path = "../core" }
dom = { path = "../dom" }
wasm-bindgen = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
    "Window",
    "History",
    "Location",
    "Event",
    "PopStateEvent"
]