[package]
name = "velo_router"
version = "0.1.0"
edition = "2021"

[dependencies]
velo_core = { path = "../core" }
velo_dom = { path = "../dom" }
wasm-bindgen = { workspace = true }
percent-encoding = "2.1"

[dependencies.web-sys]
workspace = true
features = ["Window", "History", "Location", "Event", "PopStateEvent"]
