[package]
name = "velo_dom"
version = "0.1.0"
edition = "2021"

[dependencies]
velo_core = { path = "../core" }
velo_macro = { path = "../macro" }
wasm-bindgen = { workspace = true }
js-sys = { workspace = true }

[dependencies.web-sys]
workspace = true
features = [
    "Document",
    "Element",
    "HtmlElement",
    "HtmlInputElement",
    "HtmlSelectElement",
    "HtmlTextAreaElement",
    "DocumentFragment",
    "Node",
    "Text",
    "Window",
    "Event",
    "MouseEvent",
    "KeyboardEvent",
    "console",
    "Storage",
    "DragEvent",
    "DataTransfer",        
    "DataTransferItemList",
    "Headers",            
    "Request",            
    "Response",           
    "History",            
    "Location",           
    "CssStyleDeclaration",
    "DomTokenList",
    "HtmlCollection",
    "DomRect"     
]